ckpt_path: /path/to/ckpt # used for testing only, add your ckpt path if you want to test the model
# weight_init: /path/to/weight_init # if you want to finetune va-vae on your own dataset, add your weight_init path

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 32
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 5001
        kl_weight: 1.0e-06
        disc_weight: 0.5
    ddconfig:
      double_z: true
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8 # batch size per GPU
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: /path/to/imagenet
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        data_root: /path/to/imagenet

lightning:
  trainer:
    devices: 8 # number of GPUs, modify it according to your settings
    num_nodes: 4 # number of nodes, modify it according to your settings
    strategy: ddp_find_unused_parameters_true
    accelerator: gpu
    max_epochs: 50
    precision: 32